import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1790223341663 implements MigrationInterface {
    name = 'InitSchema1790223341663'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "health_goals" ("goal_id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_22ce36c723a6dc7a971e872dd06" UNIQUE ("name"), CONSTRAINT "PK_cec1efe2638a4f7b9ab925607c8" PRIMARY KEY ("goal_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'authorized')`);
        await queryRunner.query(`CREATE TYPE "public"."users_bmi_category_enum" AS ENUM('underweight', 'normal', 'overweight', 'obese')`);
        await queryRunner.query(`CREATE TYPE "public"."users_activity_level_enum" AS ENUM('sedentary', 'light', 'moderate', 'active')`);
        await queryRunner.query(`CREATE TYPE "public"."users_diet_type_enum" AS ENUM('vegan', 'lacto', 'ovo', 'ovo_lacto')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'locked')`);
        await queryRunner.query(`CREATE TABLE "users" ("user_id" SERIAL NOT NULL, "full_name" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'authorized', "age" integer, "gender" character varying, "height_cm" double precision, "weight_kg" double precision, "bmi" double precision, "bmi_category" "public"."users_bmi_category_enum", "bmi_updated_at" TIMESTAMP, "activity_level" "public"."users_activity_level_enum", "diet_type" "public"."users_diet_type_enum", "current_goal_id" integer, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "shops" ("shop_id" SERIAL NOT NULL, "external_place_id" character varying NOT NULL, "name" character varying NOT NULL, "address" character varying, "latitude" double precision, "longitude" double precision, "category" character varying, "cached_at" TIMESTAMP NOT NULL, CONSTRAINT "UQ_fd77bedb1dc551474c31c276fcc" UNIQUE ("external_place_id"), CONSTRAINT "PK_a1c960b70b4f013a3b57238b58d" PRIMARY KEY ("shop_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ingredients_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "ingredients" ("ingredient_id" SERIAL NOT NULL, "ingredient_name" character varying NOT NULL, "unit" character varying NOT NULL, "description" character varying, "vegan_flag" boolean NOT NULL DEFAULT true, "avg_price_per_unit" double precision, "calories_per_100g" double precision, "protein_per_100g" double precision, "carb_per_100g" double precision, "fat_per_100g" double precision, "fiber_per_100g" double precision, "is_seasonal" boolean NOT NULL DEFAULT false, "season_months" character varying, "status" "public"."ingredients_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca1733bfdc5be587ed299844ac1" PRIMARY KEY ("ingredient_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_ingredients_source_enum" AS ENUM('MANUAL', 'PHOTO_SCAN')`);
        await queryRunner.query(`CREATE TABLE "user_ingredients" ("user_ingredient_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "ingredient_id" integer NOT NULL, "quantity" double precision, "unit" character varying, "expiry_date" date, "freshness_status" character varying, "source" "public"."user_ingredients_source_enum" NOT NULL DEFAULT 'MANUAL', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_06c3c0d4d045a6f911499b86577" PRIMARY KEY ("user_ingredient_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."recipes_difficulty_enum" AS ENUM('easy', 'medium', 'hard')`);
        await queryRunner.query(`CREATE TYPE "public"."recipes_diet_type_enum" AS ENUM('vegan', 'lacto', 'ovo', 'ovo_lacto')`);
        await queryRunner.query(`CREATE TYPE "public"."recipes_status_enum" AS ENUM('draft', 'pending_review', 'approved', 'rejected', 'removed')`);
        await queryRunner.query(`CREATE TABLE "recipes" ("recipe_id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" character varying, "instructions" text NOT NULL, "image_url" character varying, "prep_time" integer, "cook_time" integer, "servings" integer, "difficulty" "public"."recipes_difficulty_enum", "meal_type" character varying, "diet_type" "public"."recipes_diet_type_enum", "source_video_id" integer, "estimated_cost" double precision, "created_by" integer, "status" "public"."recipes_status_enum" NOT NULL DEFAULT 'draft', "approved_at" TIMESTAMP, "approved_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_df6485530f24cbcbc4c57171067" PRIMARY KEY ("recipe_id"))`);
        await queryRunner.query(`CREATE TABLE "ai_recommendations" ("recommendation_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "recipe_id" integer NOT NULL, "match_score" double precision, "match_percentage" double precision, "reason" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a97ce2bb2cc2c52635680265383" PRIMARY KEY ("recommendation_id"))`);
        await queryRunner.query(`CREATE TABLE "ai_recommendation_missing_ingredients" ("recommendation_id" integer NOT NULL, "ingredient_id" integer NOT NULL, "quantity_needed" double precision, "unit" character varying, CONSTRAINT "PK_2d789650c6948535e2858a0cb3a" PRIMARY KEY ("recommendation_id", "ingredient_id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_ingredients" ("recipe_id" integer NOT NULL, "ingredient_id" integer NOT NULL, "quantity" double precision NOT NULL, "unit" character varying NOT NULL, "note" character varying, "is_optional" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_90484480b3b2978068565ae2a2f" PRIMARY KEY ("recipe_id", "ingredient_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."categories_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "categories" ("category_id" SERIAL NOT NULL, "category_name" character varying NOT NULL, "description" character varying, "category_type" character varying, "status" "public"."categories_status_enum" NOT NULL DEFAULT 'active', "created_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_51615bef2cea22812d0dcab6e18" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_categories" ("recipe_id" integer NOT NULL, "category_id" integer NOT NULL, CONSTRAINT "PK_884e99b8acb3b0cbcdb4c584b92" PRIMARY KEY ("recipe_id", "category_id"))`);
        await queryRunner.query(`CREATE TABLE "nutrition_infos" ("nutrition_id" SERIAL NOT NULL, "recipe_id" integer NOT NULL, "calories" double precision, "protein" double precision, "carbs" double precision, "fat" double precision, "fiber" double precision, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8514074c32af5d525fdc99a7027" UNIQUE ("recipe_id"), CONSTRAINT "REL_8514074c32af5d525fdc99a702" UNIQUE ("recipe_id"), CONSTRAINT "PK_45c96ef734f575a932df6a39a04" PRIMARY KEY ("nutrition_id"))`);
        await queryRunner.query(`CREATE TABLE "meal_items" ("meal_item_id" SERIAL NOT NULL, "daily_meal_id" integer NOT NULL, "recipe_id" integer NOT NULL, "is_ai_suggested" boolean NOT NULL DEFAULT false, "added_by_user" boolean NOT NULL DEFAULT false, "portion_multiplier" double precision NOT NULL DEFAULT '1', CONSTRAINT "PK_b87d02189009df6aed56e523132" PRIMARY KEY ("meal_item_id"))`);
        await queryRunner.query(`CREATE TABLE "daily_meals" ("daily_meal_id" SERIAL NOT NULL, "weekly_plan_id" integer NOT NULL, "meal_date" date NOT NULL, "meal_type" character varying NOT NULL, "target_calories" double precision, CONSTRAINT "PK_96cda5a9c9ec08f9792c62ff369" PRIMARY KEY ("daily_meal_id"))`);
        await queryRunner.query(`CREATE TABLE "weekly_plans" ("weekly_plan_id" SERIAL NOT NULL, "meal_plan_id" integer NOT NULL, "week_number" integer NOT NULL, "week_budget" double precision, "adjusted_budget" double precision, "rollover_amount" double precision NOT NULL DEFAULT '0', "week_calorie_target" double precision, CONSTRAINT "PK_079c958c11d89b8077c1689f1e9" PRIMARY KEY ("weekly_plan_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."meal_plans_plan_type_enum" AS ENUM('weekly', 'monthly')`);
        await queryRunner.query(`CREATE TYPE "public"."meal_plans_status_enum" AS ENUM('draft', 'active', 'completed')`);
        await queryRunner.query(`CREATE TABLE "meal_plans" ("meal_plan_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "goal_id" integer, "bmi_snapshot" double precision, "plan_type" "public"."meal_plans_plan_type_enum" NOT NULL DEFAULT 'weekly', "start_date" date NOT NULL, "end_date" date NOT NULL, "has_budget" boolean NOT NULL DEFAULT false, "total_budget" double precision, "target_calories_per_day" double precision, "status" "public"."meal_plans_status_enum" NOT NULL DEFAULT 'draft', "generated_by" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b2116b49b3f21895961e226f476" PRIMARY KEY ("meal_plan_id"))`);
        await queryRunner.query(`CREATE TABLE "user_allergies" ("user_id" integer NOT NULL, "ingredient_id" integer NOT NULL, CONSTRAINT "PK_dd2d1e198378f3478048cb36633" PRIMARY KEY ("user_id", "ingredient_id"))`);
        await queryRunner.query(`CREATE TABLE "ingredient_conflicts" ("ingredient_id_1" integer NOT NULL, "ingredient_id_2" integer NOT NULL, "reason" character varying, CONSTRAINT "PK_2afd4e6bf26a0204d48e53f400b" PRIMARY KEY ("ingredient_id_1", "ingredient_id_2"))`);
        await queryRunner.query(`CREATE TABLE "votes" ("vote_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "content_type" character varying NOT NULL, "content_id" integer NOT NULL, "vote_type" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c6354f6c45a1b20cf439436939d" PRIMARY KEY ("vote_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."blogs_status_enum" AS ENUM('draft', 'pending_review', 'approved', 'rejected', 'removed')`);
        await queryRunner.query(`CREATE TABLE "blogs" ("blog_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "category_id" integer, "title" character varying NOT NULL, "content" text NOT NULL, "status" "public"."blogs_status_enum" NOT NULL DEFAULT 'draft', "approved_at" TIMESTAMP, "approved_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9728ee7386486ed6752b06983e8" PRIMARY KEY ("blog_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."videos_status_enum" AS ENUM('draft', 'pending_review', 'approved', 'rejected', 'removed')`);
        await queryRunner.query(`CREATE TABLE "videos" ("video_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "category_id" integer, "title" character varying NOT NULL, "video_url" character varying NOT NULL, "transcript_summary" text, "status" "public"."videos_status_enum" NOT NULL DEFAULT 'draft', "approved_at" TIMESTAMP, "approved_by" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b143ebc78208631fad3c886ded" PRIMARY KEY ("video_id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("comment_id" SERIAL NOT NULL, "user_id" integer NOT NULL, "content_type" character varying NOT NULL, "content_id" integer NOT NULL, "comment_text" text NOT NULL, "moderation_status" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eb0d76f2ca45d66a7de04c7c72b" PRIMARY KEY ("comment_id"))`);
        await queryRunner.query(`CREATE TABLE "chatbot_conversations" ("conversation_id" SERIAL NOT NULL, "user_id" integer, "session_id" character varying, "question" text NOT NULL, "answer" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0c367a19bbfbd5ee6d5faef2373" PRIMARY KEY ("conversation_id"))`);
        await queryRunner.query(`CREATE TABLE "trial_usages" ("session_id" character varying NOT NULL, "query_count" integer NOT NULL DEFAULT '0', "last_query_at" TIMESTAMP, CONSTRAINT "PK_32c1be5920b405893da806dc3df" PRIMARY KEY ("session_id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a4b53dd5f759c96f8be61f11e9f" FOREIGN KEY ("current_goal_id") REFERENCES "health_goals"("goal_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_ingredients" ADD CONSTRAINT "FK_edfc48c99960b6534282fdaa58d" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_ingredients" ADD CONSTRAINT "FK_ae72af3782e1aa371093767226a" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "FK_ff954b45fac4d029f31abe53246" FOREIGN KEY ("created_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "FK_bbee2b1fc93fb1d61d10d78cd66" FOREIGN KEY ("approved_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_recommendations" ADD CONSTRAINT "FK_5bf5782109cfe8fe1508591980b" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_recommendations" ADD CONSTRAINT "FK_4f52c395e12aade0021bcafd78e" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("recipe_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_recommendation_missing_ingredients" ADD CONSTRAINT "FK_0a73184f2bbdf31ae8a9190b42c" FOREIGN KEY ("recommendation_id") REFERENCES "ai_recommendations"("recommendation_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_recommendation_missing_ingredients" ADD CONSTRAINT "FK_bef0bcfe64d1bdae8840c6a61af" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "FK_f240137e0e13bed80bdf64fed53" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("recipe_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" ADD CONSTRAINT "FK_133545365243061dc2c55dc1373" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_23ad9291e0e22cdf46ae7ec5461" FOREIGN KEY ("created_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_categories" ADD CONSTRAINT "FK_bc02c647e75da3c57a2d22903db" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("recipe_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_categories" ADD CONSTRAINT "FK_0849dba2a4b41b34c64fbc5df5e" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nutrition_infos" ADD CONSTRAINT "FK_8514074c32af5d525fdc99a7027" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("recipe_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_items" ADD CONSTRAINT "FK_3198ed5425cb8c71f3a4cde9c4d" FOREIGN KEY ("daily_meal_id") REFERENCES "daily_meals"("daily_meal_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_items" ADD CONSTRAINT "FK_933d825a777fea6da489002c633" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("recipe_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "daily_meals" ADD CONSTRAINT "FK_0bc642273b5979d0b78a57bf5d4" FOREIGN KEY ("weekly_plan_id") REFERENCES "weekly_plans"("weekly_plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weekly_plans" ADD CONSTRAINT "FK_146ab3a9a8951d4f6fdcd7add0b" FOREIGN KEY ("meal_plan_id") REFERENCES "meal_plans"("meal_plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_plans" ADD CONSTRAINT "FK_a94a25c51cc9b60a3c542c98986" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meal_plans" ADD CONSTRAINT "FK_0bc8b467c77463d7477f27f0c83" FOREIGN KEY ("goal_id") REFERENCES "health_goals"("goal_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_allergies" ADD CONSTRAINT "FK_815358fe6393a9e4843b0441958" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_allergies" ADD CONSTRAINT "FK_ef3eedd6ef84cf5526a61987300" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_conflicts" ADD CONSTRAINT "FK_50272f610cad23e46d20cd24265" FOREIGN KEY ("ingredient_id_1") REFERENCES "ingredients"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_conflicts" ADD CONSTRAINT "FK_4426ebd973b09a14d6717b42f6d" FOREIGN KEY ("ingredient_id_2") REFERENCES "ingredients"("ingredient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "votes" ADD CONSTRAINT "FK_27be2cab62274f6876ad6a31641" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_57d7c984ba4a3fa3b4ea2fb5553" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_1f073a9f9720fe731423f1064cc" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_196e0d95bb0cf3192964a1a5544" FOREIGN KEY ("approved_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos" ADD CONSTRAINT "FK_900733992fb36a6d855308c0039" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos" ADD CONSTRAINT "FK_f9fe0463a9fa4899f41ab736511" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "videos" ADD CONSTRAINT "FK_1bde0c663eccb4ee26e7d8bf187" FOREIGN KEY ("approved_by") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" ADD CONSTRAINT "FK_04587ca7b98d66cb1684d38b3b2" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chatbot_conversations" DROP CONSTRAINT "FK_04587ca7b98d66cb1684d38b3b2"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "videos" DROP CONSTRAINT "FK_1bde0c663eccb4ee26e7d8bf187"`);
        await queryRunner.query(`ALTER TABLE "videos" DROP CONSTRAINT "FK_f9fe0463a9fa4899f41ab736511"`);
        await queryRunner.query(`ALTER TABLE "videos" DROP CONSTRAINT "FK_900733992fb36a6d855308c0039"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_196e0d95bb0cf3192964a1a5544"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_1f073a9f9720fe731423f1064cc"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_57d7c984ba4a3fa3b4ea2fb5553"`);
        await queryRunner.query(`ALTER TABLE "votes" DROP CONSTRAINT "FK_27be2cab62274f6876ad6a31641"`);
        await queryRunner.query(`ALTER TABLE "ingredient_conflicts" DROP CONSTRAINT "FK_4426ebd973b09a14d6717b42f6d"`);
        await queryRunner.query(`ALTER TABLE "ingredient_conflicts" DROP CONSTRAINT "FK_50272f610cad23e46d20cd24265"`);
        await queryRunner.query(`ALTER TABLE "user_allergies" DROP CONSTRAINT "FK_ef3eedd6ef84cf5526a61987300"`);
        await queryRunner.query(`ALTER TABLE "user_allergies" DROP CONSTRAINT "FK_815358fe6393a9e4843b0441958"`);
        await queryRunner.query(`ALTER TABLE "meal_plans" DROP CONSTRAINT "FK_0bc8b467c77463d7477f27f0c83"`);
        await queryRunner.query(`ALTER TABLE "meal_plans" DROP CONSTRAINT "FK_a94a25c51cc9b60a3c542c98986"`);
        await queryRunner.query(`ALTER TABLE "weekly_plans" DROP CONSTRAINT "FK_146ab3a9a8951d4f6fdcd7add0b"`);
        await queryRunner.query(`ALTER TABLE "daily_meals" DROP CONSTRAINT "FK_0bc642273b5979d0b78a57bf5d4"`);
        await queryRunner.query(`ALTER TABLE "meal_items" DROP CONSTRAINT "FK_933d825a777fea6da489002c633"`);
        await queryRunner.query(`ALTER TABLE "meal_items" DROP CONSTRAINT "FK_3198ed5425cb8c71f3a4cde9c4d"`);
        await queryRunner.query(`ALTER TABLE "nutrition_infos" DROP CONSTRAINT "FK_8514074c32af5d525fdc99a7027"`);
        await queryRunner.query(`ALTER TABLE "recipe_categories" DROP CONSTRAINT "FK_0849dba2a4b41b34c64fbc5df5e"`);
        await queryRunner.query(`ALTER TABLE "recipe_categories" DROP CONSTRAINT "FK_bc02c647e75da3c57a2d22903db"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_23ad9291e0e22cdf46ae7ec5461"`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" DROP CONSTRAINT "FK_133545365243061dc2c55dc1373"`);
        await queryRunner.query(`ALTER TABLE "recipe_ingredients" DROP CONSTRAINT "FK_f240137e0e13bed80bdf64fed53"`);
        await queryRunner.query(`ALTER TABLE "ai_recommendation_missing_ingredients" DROP CONSTRAINT "FK_bef0bcfe64d1bdae8840c6a61af"`);
        await queryRunner.query(`ALTER TABLE "ai_recommendation_missing_ingredients" DROP CONSTRAINT "FK_0a73184f2bbdf31ae8a9190b42c"`);
        await queryRunner.query(`ALTER TABLE "ai_recommendations" DROP CONSTRAINT "FK_4f52c395e12aade0021bcafd78e"`);
        await queryRunner.query(`ALTER TABLE "ai_recommendations" DROP CONSTRAINT "FK_5bf5782109cfe8fe1508591980b"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "FK_bbee2b1fc93fb1d61d10d78cd66"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "FK_ff954b45fac4d029f31abe53246"`);
        await queryRunner.query(`ALTER TABLE "user_ingredients" DROP CONSTRAINT "FK_ae72af3782e1aa371093767226a"`);
        await queryRunner.query(`ALTER TABLE "user_ingredients" DROP CONSTRAINT "FK_edfc48c99960b6534282fdaa58d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a4b53dd5f759c96f8be61f11e9f"`);
        await queryRunner.query(`DROP TABLE "trial_usages"`);
        await queryRunner.query(`DROP TABLE "chatbot_conversations"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "videos"`);
        await queryRunner.query(`DROP TYPE "public"."videos_status_enum"`);
        await queryRunner.query(`DROP TABLE "blogs"`);
        await queryRunner.query(`DROP TYPE "public"."blogs_status_enum"`);
        await queryRunner.query(`DROP TABLE "votes"`);
        await queryRunner.query(`DROP TABLE "ingredient_conflicts"`);
        await queryRunner.query(`DROP TABLE "user_allergies"`);
        await queryRunner.query(`DROP TABLE "meal_plans"`);
        await queryRunner.query(`DROP TYPE "public"."meal_plans_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."meal_plans_plan_type_enum"`);
        await queryRunner.query(`DROP TABLE "weekly_plans"`);
        await queryRunner.query(`DROP TABLE "daily_meals"`);
        await queryRunner.query(`DROP TABLE "meal_items"`);
        await queryRunner.query(`DROP TABLE "nutrition_infos"`);
        await queryRunner.query(`DROP TABLE "recipe_categories"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_status_enum"`);
        await queryRunner.query(`DROP TABLE "recipe_ingredients"`);
        await queryRunner.query(`DROP TABLE "ai_recommendation_missing_ingredients"`);
        await queryRunner.query(`DROP TABLE "ai_recommendations"`);
        await queryRunner.query(`DROP TABLE "recipes"`);
        await queryRunner.query(`DROP TYPE "public"."recipes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recipes_diet_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."recipes_difficulty_enum"`);
        await queryRunner.query(`DROP TABLE "user_ingredients"`);
        await queryRunner.query(`DROP TYPE "public"."user_ingredients_source_enum"`);
        await queryRunner.query(`DROP TABLE "ingredients"`);
        await queryRunner.query(`DROP TYPE "public"."ingredients_status_enum"`);
        await queryRunner.query(`DROP TABLE "shops"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_diet_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_activity_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_bmi_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "health_goals"`);
    }

}
